chore: add initial yarn.lock file

diff --git a/worker/Dockerfile b/worker/Dockerfile
--- a/worker/Dockerfile
+++ b/worker/Dockerfile
@@ -1,22 +1,36 @@
-# The reason why we seperate build and runtime stages is to optimize the final image size
 # Build stage
 FROM node:20-alpine AS builder
+
+# yarn registry + retry config
+RUN yarn config set registry https://registry.npmmirror.com
+RUN yarn config set network-timeout 600000
+
 WORKDIR /app
-COPY package*.json ./
-RUN npm install
+
+COPY package.json yarn.lock ./
+RUN yarn install --frozen-lockfile
+
 COPY . .
-RUN npm run build
+RUN yarn build
+
+
 
 # Runtime stage
 FROM node:20-alpine
+
 WORKDIR /app
-COPY package*.json ./
-RUN npm install --production
-# Copy built files and environment variables
+
+# only production deps
+COPY package.json yarn.lock ./
+RUN yarn install --production --frozen-lockfile
+
+# copy built files
 COPY --from=builder /app/dist ./dist
 COPY .env .env
-# Start the application
-CMD ["node", "dist/main.js"]
 
-HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "executable" ]
-RUN curl --fail http://localhost:3000/health || exit 1
+EXPOSE 3000
+
+HEALTHCHECK --interval=30s --timeout=10s \
+  CMD wget -q --spider http://localhost:3000/health || exit 1
+
+CMD ["node", "dist/main.js"]
